<?php
/**
 * mail() Delivery Diagnostic — Healing Therapy Center
 *
 * TEMPORARY TROUBLESHOOTING TOOL. Fires a single test email through the same
 * mail() mechanism the contact/appointment handlers use, then reports whether
 * PHP accepted it for delivery plus basic MTA config.
 *
 * Usage:  /forms/mailtest.php?key=CHANGE_ME_2024
 *
 * SECURITY:
 *   - Only sends to the fixed address below (never user-controllable) — cannot
 *     be abused as an open relay.
 *   - Gated behind a secret key so bots/random hits can't trigger mail.
 *
 * >>> DELETE THIS FILE FROM THE SERVER ONCE TESTING IS DONE. <<<
 */

// Change this before deploying, then use ?key=... to run the test.
$SECRET_KEY = 'CHANGE_ME_2024';

$EmailTo = 'info@healingtherapycenter.com';

header('Content-Type: text/html; charset=UTF-8');

// --- Access gate -----------------------------------------------------------
if (!isset($_GET['key']) || !hash_equals($SECRET_KEY, $_GET['key'])) {
    http_response_code(403);
    echo '<p style="font-family:Arial,sans-serif">Forbidden. Append <code>?key=YOUR_SECRET</code> to run the mail test.</p>';
    exit;
}

// --- Send test email -------------------------------------------------------
$submittedAt = date('l, F j, Y \a\t g:i A');
$subject = 'Healing Therapy Center — mail() delivery test (' . date('Y-m-d H:i:s') . ')';
$headers = [
    'From: Healing Therapy Center <info@healingtherapycenter.com>',
    'Reply-To: info@healingtherapycenter.com',
    'X-Mailer: PHP/' . phpversion(),
    'MIME-Version: 1.0',
    'Content-Type: text/html; charset=UTF-8',
    'X-Priority: 3'
];
$body = '<div style="font-family:Arial,sans-serif;font-size:14px;color:#17394D">'
      . '<p>This is a <strong>test message</strong> from the Healing Therapy Center mail diagnostic.</p>'
      . '<p>If you are reading this in the inbox, PHP <code>mail()</code> delivery is working.</p>'
      . '<p>Sent: ' . $submittedAt . '</p>'
      . '<p style="color:#9AA5AC;font-size:12px">Generated by /forms/mailtest.php — delete this file after testing.</p>'
      . '</div>';

$result = mail($EmailTo, $subject, $body, implode("\r\n", $headers));

// --- Report ----------------------------------------------------------------
$ok = $result ? 'TRUE'  : 'FALSE';
$okColor = $result ? '#2E7D32' : '#B4634F';
$sendmailPath = ini_get('sendmail_path') ?: '(not set)';
$hostname = gethostname() ?: '(unknown)';

echo '<div style="font-family:Arial,sans-serif;max-width:640px;margin:40px auto;color:#17394D">';
echo '<h1 style="font-size:20px">mail() Delivery Diagnostic</h1>';
echo '<p style="font-size:16px">Sent to <strong>' . htmlspecialchars($EmailTo) . '</strong></p>';
echo '<p style="font-size:18px"><strong>mail() returned:</strong> '
   . '<span style="color:' . $okColor . ';font-weight:bold">' . $ok . '</span></p>';
echo '<hr style="border:none;border-top:1px solid #EEEAE2;margin:20px 0">';
echo '<table style="border-collapse:collapse;font-size:14px">';
echo '<tr><td style="padding:6px 16px 6px 0;color:#82977F">PHP version</td><td>' . htmlspecialchars(phpversion()) . '</td></tr>';
echo '<tr><td style="padding:6px 16px 6px 0;color:#82977F">sendmail_path</td><td>' . htmlspecialchars($sendmailPath) . '</td></tr>';
echo '<tr><td style="padding:6px 16px 6px 0;color:#82977F">Server hostname</td><td>' . htmlspecialchars($hostname) . '</td></tr>';
echo '<tr><td style="padding:6px 16px 6px 0;color:#82977F">Timestamp</td><td>' . htmlspecialchars($submittedAt) . '</td></tr>';
echo '</table>';
echo '<hr style="border:none;border-top:1px solid #EEEAE2;margin:20px 0">';
echo '<p style="font-size:14px"><strong>Next:</strong> check the <strong>' . htmlspecialchars($EmailTo)
   . '</strong> inbox <em>and the spam/junk folder</em> for the test message.</p>';
echo '<ul style="font-size:14px;line-height:1.6">';
echo '<li><strong>Returned TRUE and it arrives in the inbox</strong> → mail delivery is healthy.</li>';
echo '<li><strong>Returned TRUE but lands in spam / never arrives</strong> → domain deliverability issue (check SPF/DKIM DNS for healingtherapycenter.com).</li>';
echo '<li><strong>Returned FALSE</strong> → the server MTA (sendmail/postfix) is not configured or is refusing mail.</li>';
echo '</ul>';
echo '<p style="color:#B4634F;font-weight:bold;font-size:14px">Remember to delete /forms/mailtest.php from the server when done.</p>';
echo '</div>';
?>
